from typing import List, Literal
from pydantic import BaseModel, Field


class SubTask(BaseModel):
    """A decomposed subtask assigned to a specific specialist agent."""

    id: str = Field(
        description="Unique identifier for the subtask, e.g. 'task_research', 'task_content', 'task_financial'"
    )
    agent_type: Literal["research", "content", "financial"] = Field(
        description="The specialist agent responsible for this subtask"
    )
    title: str = Field(
        description="Short descriptive title of the subtask"
    )
    instructions: str = Field(
        description="Detailed prompt, context, and requirements for the assigned agent"
    )


class TaskDecomposition(BaseModel):
    """Structured decomposition plan generated by the Supervisor Agent."""

    plan_summary: str = Field(
        description="Strategic summary of the task decomposition and delegation rationale"
    )
    subtasks: List[SubTask] = Field(
        default_factory=list,
        description="List of subtasks delegated to specialist agents (research, content, financial)"
    )


class ResearchReport(BaseModel):
    """Market and domain research report produced by ResearchAgent."""

    summary: str = Field(
        description="Executive summary of market research and landscape findings"
    )
    market_trends: List[str] = Field(
        default_factory=list,
        description="Key current industry and market trends"
    )
    competitors: List[str] = Field(
        default_factory=list,
        description="Key competitors or alternative solutions in this space"
    )
    key_findings: List[str] = Field(
        default_factory=list,
        description="Critical takeaways, insights, or data points"
    )
    opportunities: List[str] = Field(
        default_factory=list,
        description="Identified market gaps, growth vectors, or strategic opportunities"
    )


class ContentPlan(BaseModel):
    """Messaging and content strategy produced by ContentAgent."""

    headline: str = Field(
        description="Compelling hook or launch campaign headline"
    )
    core_messaging: str = Field(
        description="Core narrative and unique value proposition statements"
    )
    target_channels: List[str] = Field(
        default_factory=list,
        description="Primary distribution and outreach channels"
    )
    content_pieces: List[str] = Field(
        default_factory=list,
        description="Recommended content assets, copy outlines, or messaging deliverables"
    )
    call_to_action: str = Field(
        description="Primary call-to-action (CTA) for the audience"
    )


class FinancialAssessment(BaseModel):
    """Financial modeling and feasibility assessment produced by FinancialAgent."""

    estimated_setup_cost: str = Field(
        description="Initial capital expenditure or development setup cost estimate"
    )
    recurring_costs: List[str] = Field(
        default_factory=list,
        description="Breakdown of estimated ongoing operating expenses"
    )
    revenue_streams: List[str] = Field(
        default_factory=list,
        description="Monetization models and pricing tiers/revenue sources"
    )
    break_even_timeline: str = Field(
        description="Estimated timeline and milestones to reach break-even / profitability"
    )
    financial_risks: List[str] = Field(
        default_factory=list,
        description="Potential fiscal risks, cost drivers, or sensitivities"
    )


class ConsolidatedReport(BaseModel):
    """Final aggregated response synthesized by the Supervisor Agent."""

    executive_summary: str = Field(
        description="High-level synthesized summary of the entire strategic initiative"
    )
    strategic_analysis: str = Field(
        description="Synthesized strategic perspective blending research, content, and finance"
    )
    research_highlights: str = Field(
        description="Synthesis of market landscape, competitors, and trends"
    )
    content_strategy_summary: str = Field(
        description="Synthesis of campaign messaging and go-to-market communication"
    )
    financial_outlook: str = Field(
        description="Synthesis of cost feasibility, revenue model, and financial projections"
    )
    action_items: List[str] = Field(
        default_factory=list,
        description="Prioritized, concrete next steps for execution"
    )
