from datetime import datetime
from typing import List, Literal
from pydantic import BaseModel, Field


class SubTask(BaseModel):
    """A decomposed subtask assigned to a specific specialist agent."""

    id: str = Field(
        description="Unique identifier for the subtask, e.g. 'task_research', 'task_content', 'task_financial'"
    )
    agent_type: Literal["research", "content", "financial", "cost", "pricing"] = Field(
        description="The specialist agent responsible for this subtask"
    )
    title: str = Field(
        description="Short descriptive title of the subtask"
    )
    instructions: str = Field(
        description="Detailed prompt, context, and requirements for the assigned agent"
    )


class TaskDecomposition(BaseModel):
    """Structured decomposition plan generated by the Supervisor Agent."""

    plan_summary: str = Field(
        description="Strategic summary of the task decomposition and delegation rationale"
    )
    subtasks: List[SubTask] = Field(
        default_factory=list,
        description="List of subtasks delegated to specialist agents (research, content, financial)"
    )


class ResearchReport(BaseModel):
    """Market and domain research report produced by ResearchAgent."""

    summary: str = Field(
        description="Executive summary of market research and landscape findings"
    )
    market_trends: List[str] = Field(
        default_factory=list,
        description="Key current industry and market trends"
    )
    competitors: List[str] = Field(
        default_factory=list,
        description="Key competitors or alternative solutions in this space"
    )
    key_findings: List[str] = Field(
        default_factory=list,
        description="Critical takeaways, insights, or data points"
    )
    opportunities: List[str] = Field(
        default_factory=list,
        description="Identified market gaps, growth vectors, or strategic opportunities"
    )


class ContentPlan(BaseModel):
    """Messaging and content strategy produced by ContentAgent."""

    headline: str = Field(
        description="Compelling hook or launch campaign headline"
    )
    core_messaging: str = Field(
        description="Core narrative and unique value proposition statements"
    )
    target_channels: List[str] = Field(
        default_factory=list,
        description="Primary distribution and outreach channels"
    )
    content_pieces: List[str] = Field(
        default_factory=list,
        description="Recommended content assets, copy outlines, or messaging deliverables"
    )
    call_to_action: str = Field(
        description="Primary call-to-action (CTA) for the audience"
    )


class FinancialAssessment(BaseModel):
    """Financial modeling and feasibility assessment produced by FinancialAgent."""

    estimated_setup_cost: str = Field(
        description="Initial capital expenditure or development setup cost estimate"
    )
    recurring_costs: List[str] = Field(
        default_factory=list,
        description="Breakdown of estimated ongoing operating expenses"
    )
    revenue_streams: List[str] = Field(
        default_factory=list,
        description="Monetization models and pricing tiers/revenue sources"
    )
    break_even_timeline: str = Field(
        description="Estimated timeline and milestones to reach break-even / profitability"
    )
    financial_risks: List[str] = Field(
        default_factory=list,
        description="Potential fiscal risks, cost drivers, or sensitivities"
    )


class ConsolidatedReport(BaseModel):
    """Final aggregated response synthesized by the Supervisor Agent."""

    executive_summary: str = Field(
        description="High-level synthesized summary of the entire strategic initiative"
    )
    strategic_analysis: str = Field(
        description="Synthesized strategic perspective blending research, content, and finance"
    )
    research_highlights: str = Field(
        description="Synthesis of market landscape, competitors, and trends"
    )
    content_strategy_summary: str = Field(
        description="Synthesis of campaign messaging and go-to-market communication"
    )
    financial_outlook: str = Field(
        description="Synthesis of cost feasibility, revenue model, and financial projections"
    )
    action_items: List[str] = Field(
        default_factory=list,
        description="Prioritized, concrete next steps for execution"
    )


# ---------------------------------------------------------------------------
# Hierarchical multi-agent architecture schemas
# (CEO -> Marketing/Finance Managers -> specialist agents)
# ---------------------------------------------------------------------------


class CostAssessment(BaseModel):
    """Cost-focused financial analysis produced by CostAgent."""

    estimated_setup_cost: str = Field(
        description="Initial capital expenditure or development setup cost estimate"
    )
    recurring_costs: List[str] = Field(
        default_factory=list,
        description="Breakdown of estimated ongoing operating expenses"
    )
    break_even_timeline: str = Field(
        description="Estimated timeline and milestones to reach break-even / profitability"
    )
    cost_risks: List[str] = Field(
        default_factory=list,
        description="Potential cost overruns, drivers, or sensitivities"
    )


class PricingStrategy(BaseModel):
    """Revenue and pricing strategy produced by PricingAgent."""

    pricing_model: str = Field(
        description="Overall pricing model/approach (e.g. tiered SaaS, usage-based, one-time purchase)"
    )
    pricing_tiers: List[str] = Field(
        default_factory=list,
        description="Specific pricing tiers or packages with price points"
    )
    revenue_streams: List[str] = Field(
        default_factory=list,
        description="Monetization models and revenue sources"
    )
    pricing_risks: List[str] = Field(
        default_factory=list,
        description="Risks related to pricing sensitivity, competition, or willingness-to-pay"
    )


class MarketingReport(BaseModel):
    """Marketing Manager's synthesis of ResearchAgent + ContentAgent outputs."""

    summary: str = Field(
        description="Executive summary of the overall marketing strategy and market position"
    )
    market_positioning: str = Field(
        description="Synthesized positioning statement blending research findings and messaging strategy"
    )
    key_research_insights: List[str] = Field(
        default_factory=list,
        description="Most important research findings that inform the marketing strategy"
    )
    messaging_summary: str = Field(
        description="Condensed summary of the core messaging and content strategy"
    )
    recommended_channels: List[str] = Field(
        default_factory=list,
        description="Recommended distribution/marketing channels"
    )


class FinanceReport(BaseModel):
    """Finance Manager's synthesis of CostAgent + PricingAgent outputs."""

    summary: str = Field(
        description="Executive summary of the overall financial strategy and outlook"
    )
    cost_overview: str = Field(
        description="Condensed summary of setup/recurring costs and break-even outlook"
    )
    pricing_overview: str = Field(
        description="Condensed summary of the pricing strategy and revenue streams"
    )
    financial_risks: List[str] = Field(
        default_factory=list,
        description="Combined financial risks from both cost and pricing analysis"
    )


class ExecutiveReport(BaseModel):
    """CEO's final synthesis of MarketingReport + FinanceReport into an executive report."""

    executive_summary: str = Field(
        description="High-level synthesized summary of the entire strategic initiative"
    )
    strategic_analysis: str = Field(
        description="Synthesized strategic perspective blending marketing and finance"
    )
    marketing_highlights: str = Field(
        description="Synthesis of the Marketing Manager's report"
    )
    finance_highlights: str = Field(
        description="Synthesis of the Finance Manager's report"
    )
    action_items: List[str] = Field(
        default_factory=list,
        description="Prioritized, concrete next steps for execution"
    )


class AgentHandoff(BaseModel):
    """Structured audit record for an explicit transfer of work."""

    from_agent: str
    to_agent: str
    reason: str
    timestamp: datetime


class AgentMessage(BaseModel):
    """A visible message exchanged directly between peer agents."""

    sender: Literal["research", "finance", "content"]
    recipient: Literal["research", "finance", "content"]
    message_type: Literal["request", "response", "handoff", "insight"]
    content: str


class LaunchSynthesis(BaseModel):
    """Final launch readout produced from the three peer deliverables."""

    executive_summary: str
    market_thesis: str
    messaging_direction: str
    financial_direction: str
    action_items: List[str] = Field(default_factory=list)