from typing import List
from pydantic import BaseModel, Field


class ProductBrief(BaseModel):
    """Product brief schema generated by the PM agent."""

    name: str = Field(description="The name of the proposed product")
    description: str = Field(description="High-level product overview and value proposition")
    target_audience: str = Field(description="Target demographics and users")
    key_features: List[str] = Field(
        default_factory=list, description="Key features of the product"
    )


class TechnicalArchitecture(BaseModel):
    """Technical architecture schema generated by the Tech Lead agent."""

    tech_stack: List[str] = Field(
        default_factory=list, description="List of components in the tech stack"
    )
    database_design: str = Field(description="High-level database design or schema description")
    api_specs: str = Field(description="Key API endpoints or architectural interfaces")
    risk_assessment: str = Field(description="Potential tech stack risks or mitigations")


class MarketingPlan(BaseModel):
    """Marketing and copy plan schema generated by the Marketing agent."""

    tagline: str = Field(description="Product launch tagline")
    marketing_channels: List[str] = Field(
        default_factory=list, description="Proposed marketing acquisition channels"
    )
    launch_strategy: str = Field(description="Brief launch plan and scheduling ideas")


class FinalLaunchArtifact(BaseModel):
    """Consolidated product launch blueprint package."""

    brief: ProductBrief
    tech_specs: TechnicalArchitecture
    marketing: MarketingPlan
